GO
-- Data for TripGuide
GO
INSERT INTO TripGuide VALUES (1, 4);
INSERT INTO TripGuide VALUES (1, 5);
INSERT INTO TripGuide VALUES (2, 1);
INSERT INTO TripGuide VALUES (2, 2);
INSERT INTO TripGuide VALUES (3, 2);
INSERT INTO TripGuide VALUES (3, 5);
INSERT INTO TripGuide VALUES (4, 4);
INSERT INTO TripGuide VALUES (5, 3);
INSERT INTO TripGuide VALUES (6, 1);
INSERT INTO TripGuide VALUES (6, 4);
INSERT INTO TripGuide VALUES (7, 1);
INSERT INTO TripGuide VALUES (7, 2);
INSERT INTO TripGuide VALUES (8, 2);
INSERT INTO TripGuide VALUES (8, 5);
INSERT INTO TripGuide VALUES (9, 1);
INSERT INTO TripGuide VALUES (9, 4);
INSERT INTO TripGuide VALUES (10, 3);
INSERT INTO TripGuide VALUES (11, 2);
INSERT INTO TripGuide VALUES (12, 1);
INSERT INTO TripGuide VALUES (12, 5);
INSERT INTO TripGuide VALUES (13, 2);
INSERT INTO TripGuide VALUES (13, 5);
INSERT INTO TripGuide VALUES (14, 1);
INSERT INTO TripGuide VALUES (14, 4);
INSERT INTO TripGuide VALUES (15, 3);
INSERT INTO TripGuide VALUES (16, 1);
