name: Deploy API to Azure

on:
  push:
    branches: [ master, main ]
    paths:
      - 'TravelOrganizationSystem/WebAPI/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'travel-api-matija'    
  AZURE_WEBAPP_PACKAGE_PATH: './TravelOrganizationSystem/WebAPI'
  DOTNET_VERSION: '8.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build and test'
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./output

    - name: 'Create deployment package'
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/output
        zip -r ../../../api-deploy.zip .
        
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './api-deploy.zip' 