name: Deploy WebApp

on:
  push:
    branches: [ master ]
    paths:
      - 'TravelOrganizationSystem/WebApp/**'
      - '.github/workflows/deploy-webapp.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore TravelOrganizationSystem/WebApp/WebApp.csproj
    
    - name: Build
      run: dotnet build TravelOrganizationSystem/WebApp/WebApp.csproj --no-restore --configuration Release
    
    - name: Test
      run: dotnet test TravelOrganizationSystem/WebApp.Tests/WebApp.Tests.csproj --no-build --verbosity normal --configuration Release
    
    - name: Publish
      run: dotnet publish TravelOrganizationSystem/WebApp/WebApp.csproj --no-build --configuration Release --output ./webapp-publish
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./webapp-publish