name: Deploy API

on:
  push:
    branches: [ master ]
    paths:
      - 'TravelOrganizationSystem/WebAPI/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore TravelOrganizationSystem/WebAPI/WebApi.csproj
    
    - name: Build
      run: dotnet build TravelOrganizationSystem/WebAPI/WebApi.csproj --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --configuration Release --logger "console;verbosity=detailed"
      working-directory: TravelOrganizationSystem/WebAPI.Tests
    
    - name: Publish
      run: dotnet publish TravelOrganizationSystem/WebAPI/WebApi.csproj --no-build --configuration Release --output ./api-publish
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: travel-api-matija
        package: ./api-publish