name: Deploy API

on:
  push:
    branches: [ master ]
    paths:
      - 'TravelOrganizationSystem/WebAPI/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore TravelOrganizationSystem/WebAPI/WebApi.csproj
    
    - name: Build
      run: dotnet build TravelOrganizationSystem/WebAPI/WebApi.csproj --no-restore --configuration Release
    
    - name: Test
      run: dotnet test TravelOrganizationSystem/WebAPI.Tests/WebAPI.Tests.csproj --no-build --verbosity normal --configuration Release
    
    - name: Publish
      run: dotnet publish TravelOrganizationSystem/WebAPI/WebApi.csproj --no-build --configuration Release --output ./api-publish
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_API_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
        package: ./api-publish